post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer HGftrdsyhnBGVcerTbyjshajIre.eyJ1JhureuNOEaojJoiNJIJGBYTOiI1ZDg0OGYzYzdkZTAyNzM1MTgwYzZkZWIiLCJpYXQiOjE1Njg5Njg1MTR9._tpVOxVUHgHiIhBgkjfLLMdw78VG6cdV

{
  "title": "Hardy santa",
  "author": "Paras",
  "url": "Aajtek.com",
  "likes": 13
}
